services:
  droneManager:
    image: drone_manager:latest
    container_name: droneManager
    env_file:
      - ./droneManager/config/envs/droneManager.env
      - ./droneManager/config/envs/droneManager.env.secrets
    ports:
      - 9005:9005
    networks:
      - backend-network
    depends_on:
      droneDB:
        condition: service_healthy
        restart: true
      minio:
        condition: service_healthy
        restart: true

  droneDB:
    image: drone_db:latest
    container_name: droneDB
    env_file:
      - ./droneDB/config/envs/postgres.env
      - ./droneDB/config/envs/postgres.env.secrets
    volumes:
      - ./droneDB/data:/var/lib/postgresql/data
      - ./droneDB/init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 3s
    networks:
      - backend-network

  minio:
    image: minio:latest
    container_name: minio
    env_file:
      - ./minio/config/envs/minio.env.secrets
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_S3_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ./minio/data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9000/minio/health/live || curl -fs https://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 3s
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge
